import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib as mpl

#_______________________________________________________________
pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', 1000)

mpl.style.use('ggplot')  # optional: for ggplot-like style
#_______________________________________________________________
file_name ='C:\\Users\\0487\\Downloads\\Canada.csv'
df_can = pd.read_csv(file_name)
print(df_can.head())
print(df_can.shape)
#_______________________________________________________________
df_can.set_index('Country', inplace=True)
#______________________________________________________
# custom_colors = ['gold', 'lightcoral', 'green', 'lightskyblue', 'lightgreen']
# df_continents = df_can.groupby('Continent', axis=0).sum()
# print(df_continents)
# df_continents.plot(kind='pie', y='Total', autopct='%1.1f%%', legend=False, colors=custom_colors)
# plt.axis('equal')
# plt.show()
#
# df_continents_pivot = df_continents.pivot_table(index= 'Region', values= 'Total')
#
# print(df_continents_pivot.head(10))
# print(df_can.loc[['Afghanistan', 'Ukraine'], 'Total'])
#_______________________________________________________________
colors_list = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'lightgreen', 'pink']
explode_list = [0.1, 0, 0, 0, 0.1, 0.1] # ratio for each continent with which to offset each wedge.


df_continents = df_can.groupby('Continent', axis=0).sum()
df_continents['Total'].plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=10,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.5,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            #colors=colors_list,  # add custom colors
                            #explode=explode_list # 'explode' lowest 3 continents
                            )

# scale the title up by 12% to match pctdistance
plt.title('Immigration to Canada by Continent [1980 - 2013]', y=1.1, fontsize = 15)

plt.axis('equal')

# add legend
plt.legend(labels=df_continents.index, loc='upper left', fontsize=7)

plt.show()